
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // The CLI (migrations, introspection) must use the session-mode pooler;
  // the app's runtime client uses DATABASE_URL from schema.prisma.
  datasource: {
    url: env("DIRECT_URL"),
  },
});

